const THEMES = [
    "separating the trash",
    "reducing plastic usage",
    "planting trees",
    "conserving water",
    "recycling paper",
    "picking up litter",
    "reducing energy consumption",
    "composting organic waste",
    "reducing carbon footprint",
    "advocating for environmental policies",
    "reducing water waste",
    "using eco-friendly transportation",
    "participating in a beach cleanup",
    "supporting local sustainable farming",
    "reducing food waste",
    "advocating for renewable energy",
    "participating in a community garden",
    "promoting wildlife conservation",
    "reducing air pollution",
    "participating in a recycling drive",
    "educating others about environmental issues",
    "cleaning up local parks",
    "promoting sustainable fashion",
    "supporting wildlife rehabilitation",
    "reducing single-use plastics",
    "conserving electricity",
    "participating in coastal cleanup",
    "advocating for clean air",
    "volunteering at a local animal shelter",
    "promoting sustainable agriculture",
    "reducing food packaging waste",
    "raising awareness about endangered species",
    "advocating for sustainable fishing practices",
    "participating in community tree planting",
    "supporting renewable energy initiatives",
    "reducing paper usage",
    "volunteering at a local environmental organization",
    "promoting water conservation",
    "reducing household waste",
    "participating in a neighborhood cleanup",
    "advocating for green building practices",
    "supporting local biodiversity conservation",
];

const QUEST_THEMES = [...new Set(THEMES)];

export default QUEST_THEMES;
